### ISSUE TITLE
no valid OpenPGP data found when trying to add repositories on ubuntu 

### ISSUE THREAD

**Issue by arashmo** [samuong/alpaca#49] opened 2020-03-04 17:18 UTC
sudo add-apt-repository ppa:graphics-drivers/ppa

gpg: keyring `/tmp/tmpm22_n592/secring.gpg' created
gpg: keyring `/tmp/tmpm22_n592/pubring.gpg' created
gpg: requesting key 1118213C from hkp server keyserver.ubuntu.com
**gpgkeys: key 2388FF3BE10A76F638F80723FCAE110B1118213C can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
Failed to add key.**

tailf /var/log/syslog 
Mar  4 12:07:49 m84116293-HP-ProDesk-600-G3-PCI-MT alpaca[21627]: 2020/03/04 12:07:49 proxyfinder.go:92: [3408] CONNECT //launchpad.net:443 via "PROXY proxy.lan:8080 "
Mar  4 12:07:51 m84116293-HP-ProDesk-600-G3-PCI-MT alpaca[21627]: 2020/03/04 12:07:51 proxyfinder.go:92: [3409] CONNECT //launchpad.net:443 via "PROXY proxy.lan:8080 "
Mar  4 12:07:51 m84116293-HP-ProDesk-600-G3-PCI-MT alpaca[21627]: 2020/03/04 12:07:51 proxyfinder.go:92: [3410] GET http://keyserver.ubuntu.com:80/pks/lookup?op=get&options=mr&search=0x2388FF3BE10A76F638F80723FCAE110B1118213C via "PROXY proxy.lan:8080 "

**Comment by camh-** [comment] 2020-03-05 00:36
I am able to successfully retrieve the URL http://keyserver.ubuntu.com:80/pks/lookup?op=get&options=mr&search=0x2388FF3BE10A76F638F80723FCAE110B1118213C via alpaca. Perhaps this is a problem with your proxy (`proxy.lan:8080`) ?

**Comment by samuong** [comment] 2020-03-05 03:10
It's possible that, for whatever reason, alpaca is failing to authenticate to proxy.lan:8080 (this could be because of a bug in alpaca, but could also be an issue with the proxy server or your proxy configuration). What do you get when you run the following command?

```
curl -D- 'http://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x2388FF3BE10A76F638F80723FCAE110B1118213C'
```

**Comment by arashmo** [comment] 2020-03-05 19:13
so weird when i do  curl -D- http://key-server the certs just get printed on the screen and if immediately do add-apt-repositories the key also get imported.

i think something is wrong with ntlm authentication and the way apt-add-repositories works

**Comment by arashmo** [comment] 2020-03-05 19:21
what i found is that it does  the ntlm-auth at beginning and once to get into import key it sends the packet without auth

**Comment by samuong** [comment] 2020-03-06 02:16
If alpaca fails to do the ntlm auth with the proxy, I would expect you to get a 407 (proxy auth required) rather than a 200 (ok) response. So it looks like, if the proxy is requiring authentication, alpaca is doing it.

How have you configured curl and add-apt-repository to use the proxy? If you followed the instructions in the README, you might've done something like `export http_proxy=http://localhost:3128`. If you run `curl`, it'll pick this up from your environment. But if you run `sudo add-apt-repository


```
sam@sams-macbook-air:~$ export http_proxy=http://localhost:3128
sam@sams-macbook-air:~$ cat whatproxy
#!/bin/sh
echo http_proxy=$http_proxy
sam@sams-macbook-air:~$ ./whatproxy 
http_proxy=http://localhost:3128
sam@sams-macbook-air:~$ sudo ./whatproxy 
http_proxy=
sam@sams-macbook-air:~$ sudo http_proxy=http://localhost:3128 ./whatproxy 
http_proxy=http://localhost:3128
```

**Comment by arashmo** [comment] 2020-03-06 15:46
i just rechecked everything again, it seems that when i do curl -D-  will get the right certificates but ad-apt-repositories fails to do the NTML authentication, there must be something wrong with connection flow as i see on my wireshark connection get closed and once openned again it gets access denied from my proxy server 
$ ./whatproxy.sh 
http_proxy=http://localhost:3129
$ sudo ./whatproxy.sh 
http_proxy=http://localhost:3129

**Comment by samuong** [comment] 2020-03-07 02:44
That's really strange. It's hard for me to guess what's going on without knowing exactly what you've done and how you've got things set up. Can you please include the following?

1. Exactly what git command did you run?
2. How did you configure git to route traffic via alpaca? (was it via `http_proxy`/`https_proxy`, did you put that in `.bashrc`/`.bash_profile` or did you just set it in the session, did you set `no_proxy` as well, did you use `git-config`, etc.)
3. What's in the alpaca log?
4. Anything else that you think might be useful, like screenshots of what you're seeing in wireshark and/or what proxy your network has

**Comment by arashmo** [comment] 2020-03-10 22:59
hi dear samoung
this is what i get, i am 100 percent sure my proxy setting is right, every single time i try to run any command i check my env and if its sudo i check it from root .


2020/03/10 18:52:02 proxyfinder.go:92: [13] CONNECT //launchpad.net:443 via "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:02 proxyfinder.go:95: [13] Warning: ignoring all but first proxy in "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:20 proxyfinder.go:92: [14] GET http://keyserver.ubuntu.com:80/pks/lookup?op=get&options=mr&search=0x2388FF3BE10A76F638F80723FCAE110B1118213C via "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:20 proxyfinder.go:95: [14] Warning: ignoring all but first proxy in "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:22 proxyfinder.go:92: [15] CONNECT //getpocket.cdn.mozilla.net:443 via "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:22 proxyfinder.go:95: [15] Warning: ignoring all but first proxy in "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:30 proxyfinder.go:92: [14] GET http://keyserver.ubuntu.com:80/pks/lookup?op=get&options=mr&search=0x2388FF3BE10A76F638F80723FCAE110B1118213C via "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:30 proxyfinder.go:95: [14] Warning: ignoring all but first proxy in "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:40 proxyfinder.go:92: [14] GET http://keyserver.ubuntu.com:80/pks/lookup?op=get&options=mr&search=0x2388FF3BE10A76F638F80723FCAE110B1118213C via "PROXY proxy.lan:8080; DIRECT"
2020/03/10 18:52:40 proxyfinder.go:95: [14] Warning: ignoring all but first proxy in "PROXY proxy.lan:8080; DIRECT"

**Comment by samuong** [comment] 2020-03-11 01:46
I can't reproduce your error, even if I hack Alpaca to always return a 407. Without knowing how you've configured your proxy and exactly how you ran `git`/`add-apt-repository`/whatever else, there's no way for me to reproduce what you're getting and investigate further. I'm sure you believe you've done this correctly, but can you share the details with me anyway?

One thing that I noticed is that there are 6 log lines with the sequence number "[14]" in it, 2 lines per request. It looks an awful lot like it's running through an NTLM handshake, which is a 3-step process. These steps are:

1. The initial request, in [proxy.go:184](https://github.com/samuong/alpaca/blob/80b4c59a2347586c6252bc7e888bd64896fe1aa8/proxy.go#L184), that tries the initial request without credentials. It's likely that `proxy.lan:8080` is returning a 407 here.
2. The "type 1" message, in [authenticator.go:82](https://github.com/samuong/alpaca/blob/80b4c59a2347586c6252bc7e888bd64896fe1aa8/authenticator.go#L82), which initiates the NTLM handshake. The proxy should respond with a "type 2" message.
3. Alpaca then sends a "type 3" message, in [authenticator.go:103](https://github.com/samuong/alpaca/blob/80b4c59a2347586c6252bc7e888bd64896fe1aa8/authenticator.go#L103), which is the final message in the handshake.

This means that Alpaca is doing the NTLM handshake. It's not clear whether this succeeded or not, but it definitely gets all the way to the end. I can think of two reasons it might not succeed:

1. Your proxy only supports an old version of NTLM. Cntlm supports a wide range of NTLM versions, whereas Alpaca uses http://github.com/Azure/go-ntlmssp, which only supports NTLMv2.
2. You mentioned in #48 that you modified Alpaca to grab your credentials from a text file so that you could run it from a systemd unit. It's possible that the credentials are still not being picked up correctly - can you please try this with an unmodified version of Alpaca with the password typed in to the console, and let us know whether this works?

It's also interesting that these requests all happen exactly 10 seconds apart - at 18:52:20, 18:52:30 and 18:52:04. I don't know whether this means anything, but it seems odd.

**Comment by samuong** [comment] 2021-11-14 04:55
Closing this as we're unable to reproduce this on our end, and it's unclear whether this is an issue with Alpaca or the upstream proxy. Please feel free to reopen if it you can provide more info on how to reproduce it.

**Closed by samuong** 2021-11-14 04:55 UTC
